#!/bin/bash

# ~/.ssh/rc
# Requires: vnstat
# Version: 20140918

# This is scp, sftp, a port forward, or something else
if [ ! -t 1 ]; then
    exit
fi

# Use stderr like the manpage tells you to do
exec 1>&2

# Commands
USER=$(who | tail -1 | awk '{print $1" "$6}')
HOSTNAME=$(uname -n)
KERNEL=$(uname -r)
CPU_NUMBER=$(grep "model name" /proc/cpuinfo | cut -d ":" -f2 | wc -l)
CPU_MODEL=$(grep "model name" /proc/cpuinfo | cut -d ":" -f2 | head -n1)
FREERAM=$(free -m | grep "buffers/cache" | awk '{ print $3}')
TOTALRAM=$(free -m | grep ^Mem | awk '{print $2}')
ARCH=$(uname -m)
TX_MONTH=$(vnstat -m | grep -vP "month|estimated|-" | tail -1 | awk '{print $6$7}')
UPTIME=$(uptime)

# The different colours as variables
W="\033[01;37m"
B="\033[01;34m"
R="\033[01;31m"

# Output
echo -e "$R#=============================================================================#"
echo -e "$W Welcome $B $USER $W to $B $HOSTNAME"                           
echo -e "$R ARCH   $W= $ARCH"                                  
echo -e "$R KERNEL $W= $KERNEL"                               
echo -e "$R CPU    $W= ($CPU_NUMBER) x$CPU_MODEL"
echo -e "$R RAM    $W= $FREERAM/$TOTALRAM MB"                                  
echo -e "$R ETH TX $W= $TX_MONTH (1TB max)"
echo -e "$R UPTIME $W=$UPTIME"                                
echo -e "$R#=============================================================================#"
tput sgr0

