#!/bin/bash

# ~/.ssh/rc
# Requires: vnstat
# Version: 2014091815

# This is scp, sftp, a port forward, or something else
if [ ! -t 1 ]; then
    exit
fi

# Use stderr like the manpage tells you to do
exec 1>&2

# Commands
USER=$(who | tail -1 | awk '{print $1" "$6}')
HOSTNAME=$(uname -n)
KERNEL=$(uname -r)
CPU_NUMBER=$(grep "model name" /proc/cpuinfo | cut -d ":" -f2 | wc -l)
CPU_MODEL=$(grep "model name" /proc/cpuinfo | cut -d ":" -f2 | head -n1)
FREERAM=$(free -m | grep "buffers/cache" | awk '{ print $3}')
TOTALRAM=$(free -m | grep ^Mem | awk '{print $2}')
ARCH=$(uname -m)
TX_MONTH=$(vnstat -m | grep -vP "month|estimated|-" | tail -1 | awk '{print $6$7}')
UPTIME=$(uptime)

# The different colours as variables
TXT_RED=$(tput setaf 1)
TXT_GREEN=$(tput setaf 2)
TXT_YELLOW=$(tput setaf 3)
TXT_BLUE=$(tput setaf 4)
# TXT_MAGENTA=$(tput setaf 5)
# TXT_CYAN=$(tput setaf 6)
TXT_WHITE=$(tput setaf 7)
TXT_BOLD=$(tput bold)
TXT_RST=$(tput sgr0)

# Output
echo "${TXT_BOLD}${TXT_RED}#=============================================================================#"
echo "${TXT_WHITE} Welcome ${TXT_BLUE} ${USER} ${TXT_WHITE} to ${TXT_BLUE} ${HOSTNAME}"                           
echo "${TXT_RED} ARCH   ${TXT_WHITE}= ${ARCH}"                                  
echo "${TXT_RED} KERNEL ${TXT_WHITE}= ${KERNEL}"                               
echo "${TXT_RED} CPU    ${TXT_WHITE}= (${CPU_NUMBER}) x${CPU_MODEL}"
echo "${TXT_RED} RAM    ${TXT_WHITE}= ${FREERAM}/${TOTALRAM} MB"                                  
echo "${TXT_RED} ETH TX ${TXT_WHITE}= ${TX_MONTH} (1TB max)"
echo "${TXT_RED} UPTIME ${TXT_WHITE}=${UPTIME}"                                
echo "${TXT_RED}#=============================================================================#"
echo -n "${TXT_RST}"
