#!/bin/sh

# ~/.ssh/rc

# Version: 20170128 (FreeBSD)

# Requires: 
# + vnstat
# + freecolor

# This is scp, sftp, a port forward, or something else
if [ ! -t 1 ]; then
    exit
fi

# Use stderr like the manpage tells you to do
exec 1>&2

# Commands
USER=$(who | tail -1 | awk '{print $1" "$6}')
HOSTNAME=$(uname -n)
# KERNEL=$(uname -r)
KERNEL=$(freebsd-version)
CPU_NUMBER=$(sysctl hw.ncpu | awk '{ print $2}')
CPU_MODEL=$(sysctl hw.model | cut -d ":" -f2)
FREERAM=$(freecolor -mo | grep ^Mem | awk '{print $3}')
TOTALRAM=$(grep "real memory" /var/run/dmesg.boot | awk {'print $5$6'})
ARCH=$(uname -m)
TRANSFER_MONTH=$(vnstat -m | grep -v "month" | grep -v "estimated" | grep -v "-" | tail -1 | awk '{print $9$10}')
FREEDISK=$(df -h / | tail -1 | awk '{ print $4 }')
UPTIME=$(uptime)

# The different colours as variables
TXT_RED='\e[0;31m'
TXT_RED_BOLD='\e[1;31m'
TXT_WHITE='\e[0;37m'
TXT_WHITE_BOLD='\e[1;37m'
TXT_RST='\e[0m'

# Output
echo -e "\n"
echo -e "${TXT_RED_BOLD}#=============================================================================#"
echo -e "${TXT_WHITE} Bienvenido ${TXT_WHITE_BOLD} ${USER} ${TXT_WHITE_BOLD}${TXT_RST} a ${TXT_WHITE_BOLD} ${HOSTNAME}"                           
echo -e "${TXT_RED_BOLD} ARCH   ${TXT_WHITE}= ${ARCH}"                                  
echo -e "${TXT_RED_BOLD} KERNEL ${TXT_WHITE}= ${KERNEL}"                               
echo -e "${TXT_RED_BOLD} CPU    ${TXT_WHITE}= (${CPU_NUMBER}) x${CPU_MODEL}"
echo -e "${TXT_RED_BOLD} RAM    ${TXT_WHITE}= ${FREERAM}MB ${TOTALRAM}"
echo -e "${TXT_RED_BOLD} RX+TX  ${TXT_WHITE}= ${TRANSFER_MONTH} (2TB max)"
echo -e "${TXT_RED_BOLD} DISK   ${TXT_WHITE}= ${FREEDISK} (20GB max)"
echo -e "${TXT_RED_BOLD} UPTIME ${TXT_WHITE}= ${UPTIME}"                                
echo -e "${TXT_RED_BOLD}#=============================================================================#${TXT_RST}"
